import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Card from "../components/Card";
import InputNumber from "../components/InputNumber";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [qtdDoors, setQtdDoors] = useState<number>(3);
  const [doorGift, setDoorGift] = useState<number>(3);
  const [btnDisabled, setBtnDisabled] = useState<boolean>(false);
  return (
    <div>
      <Head>
        <title>Monty Hall - Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.home}>
        <div>
          <Card bgColor={"#c0392c"}>
            <h1>Monty Hall</h1>
          </Card>
          <Card>
            <InputNumber
              value={qtdDoors}
              text="How many Doors?"
              handleChange={(newValue) => {
                if (newValue < 3) {
                  setQtdDoors(3);
                  setBtnDisabled(true);
                } else {
                  setQtdDoors(newValue);
                  setBtnDisabled(false);
                }
              }}
            />
          </Card>
        </div>
        <div>
          <Card>
            <InputNumber
              value={doorGift}
              text="Which door will have the gift?"
              handleChange={(newValue) => {
                if (newValue <= 0) {
                  setDoorGift(1);
                  setBtnDisabled(true);
                } else if (newValue > qtdDoors) {
                  setDoorGift(qtdDoors);
                  setBtnDisabled(false);
                } else {
                  setDoorGift(newValue);
                  setBtnDisabled(false);
                }
              }}
            />
          </Card>
          <Card bgColor={"#28a085"}>
            <Link
              href={`${btnDisabled ? "/" : `/game/${qtdDoors}/${doorGift}`}`}
            >
              <h2
                className={`${styles.link} ${
                  btnDisabled ? styles.disabled : ""
                }`}
              >
                Start
              </h2>
            </Link>
          </Card>
        </div>
      </div>
    </div>
  );
}
